on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build project
        env:
          VERSION: 0.1.${{ github.run_number }}
        run: |
          mkdir -p build && echo "VERSION = '$(version)'" > build/__version__.py
          python3 setup.py sdist bdist_wheel
      - name: Upload to PyPi
        run: |
          python3 -m pip install --user --upgrade twine
          python3 -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
